default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mike
  password: <%= ENV['rollodex_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: real_articles_development

test:
  <<: *default
  database: real_articles_test

production:
  <<: *default

  database: real_articles_production